jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: 8.15.1
      - run: node --version
      - run: npm install
      - run: npm run build
      - run: ls 
orbs:
  node: circleci/node@3.0.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - install-node-example
